services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "appuser", "-papppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: backend/
    restart: always
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: appdb
    depends_on:
      db:
        condition: service_healthy



  frontend:
    build: frontend/react/
    restart: always
    ports:
      - "4173:4173"
