x-common-env: &common-env
  env_file: .env   # добавить эту строку
  environment: &common-env-vars
    PYTHONUNBUFFERED: ${PYTHONUNBUFFERED:-1}
    POSTGRES_HOST: ${POSTGRES_HOST:-db}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    POSTGRES_USER: ${POSTGRES_USER:-appuser}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
    POSTGRES_DB: ${POSTGRES_DB:-appdb}
    QUEUEING_ROUTE: ${QUEUEING_ROUTE:-}
    COMMON_API: ${COMMON_API:-}
    REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL:-900}
    NATS_URL: ${NATS_URL:-nats://nats:4222}

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT:-3307}:3307"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 5s
      timeout: 5s
      retries: 10

  common-api:
    <<: *common-env
    build: 
      context: .
      dockerfile: api/Dockerfile
    restart: no
    ports:
      - "8000:8000"
    environment:
      <<: *common-env-vars
      PUBLIC_URL: ${PUBLIC_URL:-localhost:8000}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    <<: *common-env
    build: frontend/
    restart: always
    ports:
      - "4173:4173"

